name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-13
    steps:
      # TCCDB has the wrong screencapture values, see: https://github.com/actions/runner-images/issues/8782
      - name: labels
        run: sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "INSERT OR IGNORE INTO access VALUES('kTCCServicePostEvent','/usr/sbin/sshd',1,2,3,1,NULL,NULL,NULL,'UNUSED',NULL,0, 1702632013076);" 
      - name: Build
        run: cargo build --verbose --features ci
      - name: Run tests
        run: cargo test --verbose --features ci
    
