name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-13
    steps:
      # TCCDB has the wrong screencapture values, see: https://github.com/actions/runner-images/issues/8782
      - name: Reset tcc screencapture
        run: tccutil reset ScreenCapture
      - name: FIX ISSUE WITH MAC-OS 13 runner
        uses: guidepup/setup-action@0.13.0
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --features ci
      - name: Run tests
        run: cargo test --verbose --features ci
    
