name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-12

    
    steps:
    - uses: actions/checkout@v3
    - name: grant write permission to TCC
      run: sudo chmod 664 /Library/Application\ Support/com.apple.TCC
    - name: see terminal process
      run: launchctl list
    - name: Build
      run: cargo build --verbose --features ci
    - name: Run tests
      run: cargo test --verbose --features ci
    
